### ISSUE TITLE
Basho Bench invoked in `standalone` mode does not terminate when `Driver:run` crashes and then `Driver:new` crashes too [JIRA: TOOLS-105]

### ISSUE THREAD

**Issue by lucafavatella** [basho/basho_bench#140]
Steps to reproduce:
* Write a driver `Driver` with `new` and `run` callbacks
* Start Basho Bench in `standalone` mode with at least one worker using the driver
* (Invocation of `Driver:new` succeeds)
* Cause an invocation of `Driver:run` to crash e.g. `badmatch` (write `run` callback craftily for this to happen)
* (Basho Bench tries to restart the driver) Cause the invocation of `Driver:new` to crash e.g. `badmatch`
* Observe that basho Bench does not stop

I feel (I have not double checked) the root cause of the non-termination is the interaction between:
* The way module `basho_bench_worker` handles crashes, and
* The `init:stop` call introduced in #117.

**Comment by slfritchie** [comment]
Hi, @lucafavatella, sorry I've let this sit for so long, but I've been undecided on what to do. It is (arguably) a feature that some workers can run correctly and others crash but fail to restart correctly.  The rest of the test run can finish but with fewer functioning workers -- the ones that cannot init are simply stuck waiting and so are harmless.  But harmless also means not generating load.

I've a small branch that causes a certain failure here: https://github.com/basho/basho_bench/compare/bug/gh140 ... but I cannot decide if it's worthwhile.  Perhaps @jonmeredith or @jburwell or @jtuple or @JeetKunDoug might weigh in with an opinion?

**Comment by slfritchie** [comment]
Ping @jonmeredith or @jburwell or @jtuple or @JeetKunDoug

**Comment by JeetKunDoug** [comment]
So if we're going to do this, it would probably be good to make it configurable. I assume driver:new failures today are counted as "errors" in the run, which seems reasonable, but I could also understand the case where you'd like to jut fail the whole test run as soon as you don't have as many drivers as you wanted.

**Comment by jonmeredith** [comment]
I'd argue for let-it-crash and if people want that behavior they should tolerate disconnected clients - otherwise that worker will not be taking jobs and contributing to the throughput.  If you have specify a rate limit, you'll get below it, but not know why.  If you go for max throughput any calculations based on throughout/worker will be flawed.

The only way to know would be to trawl logs, I suppose we could count that as request errors, but that seems ignored too.

**Comment by slfritchie** [comment]
So then the https://github.com/basho/basho_bench/compare/bug/gh140 force crash thing sounds good enough?

**Comment by JeetKunDoug** [comment]
Seems like it to me. @jonmeredith ?

**Comment by slfritchie** [comment]
#186 was reviewed positively & merged, closing. Thanks, Luca, for bringing this problem to our attention.

**Comment by Basho-JIRA** [comment]
GH: "slfritchie closed this in #186 12 days ago" 

***[posted via JIRA by Scott Fritchie]***
