### ISSUE TITLE
Some bugs of http raw driver [JIRA: TOOLS-106]

### ISSUE THREAD

**Issue by shino** [basho/basho_bench#156]
- [ ] `http_raw_ips` can not be `[{{A,B,C,D}, Port =/= 80}]`. `[{"A.B.C.D", Port}]` works.
- [x] there may be off-by-one error in `http_raw_disconnect_frequency` when set to `{ops, 0}` or `{ops, 1}`.
  (further confirmation is needed)
- [ ] handling of `{error, connection_closed}` needed, because the error can  occur by race between client-side keep alive and server side active close. 
- [ ] summary may be zero for very low rate like `{rate, 1}` even there are real ops executed.

**Comment by slfritchie** [comment]
Shino, did you have any additional fixes for this issue?  Or should it be closed?

**Comment by shino** [comment]
Only second one was fixed by #160. No plan for fixing others, which are not important (at least for now). Close.
