### ISSUE TITLE
http example config crash [JIRA: TOOLS-107]

### ISSUE THREAD

**Issue by lixen** [basho/basho_bench#167]
basho_bench_driver_http.erl can call  basho_bench_valgen:new with same id many times.

This crash with badarg since it creates a ets table every time.

build_generators([{Name, {value_generator, ValGenSpec}}|Rest], Generators, Id) ->
    ValGen = basho_bench_valgen:new(ValGenSpec, Id),
    build_generators(Rest, [{Name, ValGen}|Generators], Id);

Seems to be introduced by:
https://github.com/basho/basho_bench/commit/44ee51fdeb319eed049bea2426b2d6ec5613fb8e

**Comment by slfritchie** [comment]
@lixen Howdy, I merged #168 just now.  Is this error still a problem now?

**Comment by slfritchie** [comment]
Closing due to old age and probably fixed, please reopen if I'm wrong.

**Comment by Basho-JIRA** [comment]
GH: slfritchie closed this 27 days ago 

***[posted via JIRA by Scott Fritchie]***
