### ISSUE TITLE
Update docs.basho.com page highlighting downloads and self-contained package [JIRA: TOOLS-85]

### ISSUE THREAD

**Issue by seemaj** [basho/basho_bench#171]
We have an old requirement from State Farm that we have already addressed
Self-contained Basho Bench for customers who don't have access to external packaging systems like EPEL or R's CRAN.
We need to make sure that Docs is updated so that we can point to packages that customers can download without needing to build or using external packages.
http://docs.basho.com/riak/latest/ops/building/benchmarking/

**Comment by dmitrizagidulin** [comment]
@seemaj Online docs fix expanding the installation instructions and highlighting the use of pre-built packages is pending at https://github.com/basho/basho_docs/issues/1563

**Comment by slfritchie** [comment]
@dmitrizagidulin @seemaj The issue that Dmitri refers to on March 17th is now merged.  Is anything else required for this issue?

**Comment by slfritchie** [comment]
ping?

**Comment by dmitrizagidulin** [comment]
The installation instructions have been included in the docs, and merged. Closing.

**Comment by Basho-JIRA** [comment]
The Github comments indicate that this issue is resolved, but it was left open in Jira. Not sure why this was in DevOps. Closing. 

***[posted via JIRA by Tod Bookless]***
