### ISSUE TITLE
Document (or implement) pb + Authz config [JIRA: TOOLS-87]

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho/basho_bench#173]
Does the current riakc_pb driver support username & password authentication from Riak 2.0?
If yes, let's add documentation.
If not, let's implement.

**Comment by Basho-JIRA** [comment]
There is not support via a specific option, but the below indicates it is trivial to support auth:

https://github.com/basho/basho_bench/blob/master/src/basho_bench_driver_riakc_pb.erl 

***[posted via JIRA by Sean Cribbs]***

**Comment by slfritchie** [comment]
@dmitrizagidulin Ping?

**Comment by Basho-JIRA** [comment]
Not a Docs ticket. 

***[posted via JIRA by Lauren Rother]***
