### ISSUE TITLE
Required erlang version not clear [JIRA: RCS-348]

### ISSUE THREAD

**Issue by robinbowes** [basho/basho_bench#201]
This is mostly a documentation issue, but the README states that "Erlang/OTP R13B03 or later" is required.

I have installed Erlang R14B04 (from EPEL on Oracle Linux 6.x) and get this make error:
```
$ make all
./rebar get-deps

=ERROR REPORT==== 2-Feb-2016::10:14:01 ===
beam/beam_load.c(1365): Error loading module rebar:
  use of opcode 153; this emulator supports only up to 152
```

After some searching, I found #154 from 2014 in which I read:

```The version of Erlang/OTP that you're using to try to build basho_bench appears to be R14, whereas basho_bench requires R15 or newer ... including the rebar executable that's bundled with basho_bench.```

Can you please fix the README to reflect this.

R.

**Comment by mrallen1** [comment]
Thanks for the report. I opened PR #202 to address this issue.

**Comment by slfritchie** [comment]
#202 merged, closing.  Thanks for finding the runtime version mismatch!
